steps:
  - name: 'gcr.io/k8s-skaffold/skaffold:v2.1.0'
    id: 'Build artifact'
    args:
      - 'skaffold'
      - 'build'
      - '--interactive=false'
      - '--build-image=frontend'
      - '--default-repo=${_DEFAULT_REPO}'
      - '--file-output=/workspace/artifacts.json'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    id: 'Create release'
    entrypoint: gcloud
    args:
      [
        'deploy', 'releases', 'create', 'r-${SHORT_SHA}-$$DATE$$TIME',
        '--delivery-pipeline', 'msvc-fe-gke',
        '--region', '$_REGION',
        '--build-artifacts', '/workspace/artifacts.json',
        '--skaffold-version', '2.0'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    id: 'Create Cloud Run release'
    entrypoint: gcloud
    args:
      [
        'deploy', 'releases', 'create', 'r-${SHORT_SHA}-$$DATE$$TIME',
        '--delivery-pipeline', 'msvc-fe-run',
        '--region', '$_REGION',
        '--build-artifacts', '/workspace/artifacts.json',
        '--skaffold-version', '2.0'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
