version: "3"
services:
  frontend:
    build: ./src/frontend
    volumes:
      - ~/microservices/src/frontend:/var/www/html
      - /var/www/html/vendor
    ports:
      - "9876:8080"
    environment:
      - FONT_COLOR_SVC=${MICROSERVICES_FONT_COLOR_SVC:-font_color:8080}
      - FONT_SIZE_SVC=${MICROSERVICES_FONT_SIZE_SVC:-font_size:8080}
      - WORD_SVC=${MICROSERVICES_WORD_SVC:-word:80}
      - PUBSUB_EVENTS_TOPIC=${MICROSERVICES_PUBSUB_EVENTS_TOPIC}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
  font_color:
    build: ./src/font-color
    ports:
      - "9875:8080"
  font_size:
    build: ./src/font-size
    ports:
      - "9874:8080"
  word:
    build: ./src/word
    volumes:
     - ~/.config/gcloud/application_default_credentials.json:/gcp/creds.json
    ports:
      - "9873:80"
    environment:
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
      - RANDOM_ERROR_PROBABILITY=${MICROSERVICES_WORD_SVC_RANDOM_ERROR_PROBABILITY:-0.0}
      - USE_DATABASE=true
  worker:
    build: ./src/worker
    ports:
      - "9872:8080"
    environment:
      - PORT=8080
