version: "3"
services:
  frontend:
    build: ./src/frontend
    volumes:
      - ~/microservices/src/frontend:/var/www/html
    ports:
      - "9876:8080"
    environment:
      - FONT_COLOR_SVC=${MICROSERVICES_FONT_COLOR_SVC:-font_color:8080}
      - FONT_SIZE_SVC=${MICROSERVICES_FONT_SIZE_SVC:-font_size:8080}
      - WORD_SVC=${MICROSERVICES_WORD_SVC:-word:80}
  font_color:
    build: ./src/font-color
    ports:
      - "9875:8080"
  font_size:
    build: ./src/font-size
    ports:
      - "9874:8080"
  word:
    build: ./src/word
    ports:
      - "9873:80"
    environment:
      - RANDOM_ERROR_PROBABILITY=${MICROSERVICES_WORD_SVC_RANDOM_ERROR_PROBABILITY:-0.5}
  worker:
    build: ./src/worker
    ports:
      - "9872:8080"
    environment:
      - PORT=8080
