apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: microservices
build:
  artifacts:
  - image: carlosafonso/microservices-font-color
    context: src/font-color
    docker:
      dockerfile: Dockerfile
  - image: carlosafonso/microservices-font-size
    context: src/font-size
    docker:
      dockerfile: Dockerfile
  - image: carlosafonso/microservices-frontend
    context: src/frontend
    docker:
      dockerfile: Dockerfile
  - image: carlosafonso/microservices-word
    context: src/word
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/font-color.yaml
    - kubernetes/font-size.yaml
    - kubernetes/frontend.yaml
    - kubernetes/word.yaml
portForward:
  - resourceType: service
    resourceName: frontend
    port: 80
    localPort: 9876
