apiVersion: skaffold/v3
kind: Config
metadata:
  name: microservices
build:
  artifacts:
  - image: carlosafonso/microservices-font-color
    context: src/font-color
    docker:
      dockerfile: Dockerfile
  - image: carlosafonso/microservices-font-size
    context: src/font-size
    docker:
      dockerfile: Dockerfile
  - image: carlosafonso/microservices-frontend
    context: src/frontend
    docker:
      dockerfile: Dockerfile
  - image: carlosafonso/microservices-word
    context: src/word
    docker:
      dockerfile: Dockerfile
profiles:
- name: dev
  activation:
    - command: dev
  manifests:
    rawYaml:
      - kubernetes/base/font-color.yaml
      - kubernetes/base/font-size.yaml
- name: staging
  manifests:
    kustomize:
      paths:
      - kubernetes/overlays/staging
- name: run-staging
  manifests:
    kustomize:
      paths:
      - kubernetes/knative/overlays/staging
  deploy:
    cloudrun: {}
- name: prod
  manifests:
    kustomize:
      paths:
      - kubernetes/overlays/prod
- name: run-prod
  manifests:
    kustomize:
      paths:
      - kubernetes/knative/overlays/prod
  deploy:
    cloudrun: {}
portForward:
  - resourceType: service
    resourceName: frontend
    port: 80
    localPort: 9876
