Parameters:
  FontColorImageUri:
    Type: String
    Default: public.ecr.aws/carlosafonso-aws/microservices-font-color:latest
  FontSizeImageUri:
    Type: String
    Default: public.ecr.aws/carlosafonso-aws/microservices-font-size:latest
  WordImageUri:
    Type: String
    Default: public.ecr.aws/carlosafonso-aws/microservices-word:latest
  FrontendImageUri:
    Type: String
    Default: public.ecr.aws/carlosafonso-aws/microservices-frontend:latest
  WorkerImageUri:
    Type: String
    Default: public.ecr.aws/carlosafonso-aws/microservices-worker:latest
  LogRetentionPeriod:
    Type: Number
    Default: 14
    # We are allowing some of the values supported by AWS::Logs::LogGroup.
    # See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90]
  SourceRepo:
    Type: String
    Default: https://github.com/carlosafonso/microservices.git
    Description: The URL of the master repository that will be cloned
  AL2AmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    Description: The ID of the Amazon Linux 2 AMI to use in the automation instance

Resources:
  #
  # Section: Network
  #
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./network.yaml
  #
  # End of Section: Network
  #

  #
  # Section: ECS cluster
  #
  EcsClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecs-cluster.yaml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnetAId: !GetAtt NetworkStack.Outputs.PublicSubnetAId
        PublicSubnetBId: !GetAtt NetworkStack.Outputs.PublicSubnetBId
        PrivateSubnetAId: !GetAtt NetworkStack.Outputs.PrivateSubnetAId
        PrivateSubnetBId: !GetAtt NetworkStack.Outputs.PrivateSubnetBId

  FontColorServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./font-color-svc.yaml
      Parameters:
        ClusterArn: !GetAtt EcsClusterStack.Outputs.ClusterArn
        ClusterName: !GetAtt EcsClusterStack.Outputs.ClusterName
        ClusterSecurityGroupId: !GetAtt EcsClusterStack.Outputs.ClusterSecurityGroupId
        FontColorImageUri: !Ref FontColorImageUri
        LogGroup: !Ref LogGroup
        PrivateSubnetAId: !GetAtt NetworkStack.Outputs.PrivateSubnetAId
        PrivateSubnetBId: !GetAtt NetworkStack.Outputs.PrivateSubnetBId
        ServiceRegistryNamespaceId: !GetAtt EcsClusterStack.Outputs.ServiceRegistryNamespaceId
        TaskExecutionRoleArn: !GetAtt EcsClusterStack.Outputs.TaskExecutionRoleArn

  FontSizeServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./font-size-svc.yaml
      Parameters:
        ClusterArn: !GetAtt EcsClusterStack.Outputs.ClusterArn
        ClusterName: !GetAtt EcsClusterStack.Outputs.ClusterName
        ClusterSecurityGroupId: !GetAtt EcsClusterStack.Outputs.ClusterSecurityGroupId
        FontSizeImageUri: !Ref FontSizeImageUri
        LogGroup: !Ref LogGroup
        PrivateSubnetAId: !GetAtt NetworkStack.Outputs.PrivateSubnetAId
        PrivateSubnetBId: !GetAtt NetworkStack.Outputs.PrivateSubnetBId
        ServiceRegistryNamespaceId: !GetAtt EcsClusterStack.Outputs.ServiceRegistryNamespaceId
        TaskExecutionRoleArn: !GetAtt EcsClusterStack.Outputs.TaskExecutionRoleArn

  WordServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./word-svc.yaml
      Parameters:
        ClusterArn: !GetAtt EcsClusterStack.Outputs.ClusterArn
        ClusterName: !GetAtt EcsClusterStack.Outputs.ClusterName
        ClusterSecurityGroupId: !GetAtt EcsClusterStack.Outputs.ClusterSecurityGroupId
        WordImageUri: !Ref WordImageUri
        LogGroup: !Ref LogGroup
        PrivateSubnetAId: !GetAtt NetworkStack.Outputs.PrivateSubnetAId
        PrivateSubnetBId: !GetAtt NetworkStack.Outputs.PrivateSubnetBId
        ServiceRegistryNamespaceId: !GetAtt EcsClusterStack.Outputs.ServiceRegistryNamespaceId
        TaskExecutionRoleArn: !GetAtt EcsClusterStack.Outputs.TaskExecutionRoleArn

  FrontendServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./frontend-svc.yaml
      Parameters:
        ALBBlueTargetGroupArn: !GetAtt EcsClusterStack.Outputs.ALBBlueTargetGroupArn
        ClusterArn: !GetAtt EcsClusterStack.Outputs.ClusterArn
        ClusterName: !GetAtt EcsClusterStack.Outputs.ClusterName
        ClusterSecurityGroupId: !GetAtt EcsClusterStack.Outputs.ClusterSecurityGroupId
        FrontendImageUri: !Ref FrontendImageUri
        LogGroup: !Ref LogGroup
        PrivateSubnetAId: !GetAtt NetworkStack.Outputs.PrivateSubnetAId
        PrivateSubnetBId: !GetAtt NetworkStack.Outputs.PrivateSubnetBId
        TaskExecutionRoleArn: !GetAtt EcsClusterStack.Outputs.TaskExecutionRoleArn

  WorkerServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./worker-svc.yaml
      Parameters:
        ClusterArn: !GetAtt EcsClusterStack.Outputs.ClusterArn
        ClusterName: !GetAtt EcsClusterStack.Outputs.ClusterName
        # ClusterSecurityGroupId: !GetAtt EcsClusterStack.Outputs.ClusterSecurityGroupId
        WorkerImageUri: !Ref WorkerImageUri
        JobQueueUrl: !GetAtt EcsClusterStack.Outputs.JobQueueUrl
        LogGroup: !Ref LogGroup
        PrivateSubnetAId: !GetAtt NetworkStack.Outputs.PrivateSubnetAId
        PrivateSubnetBId: !GetAtt NetworkStack.Outputs.PrivateSubnetBId
        TaskExecutionRoleArn: !GetAtt EcsClusterStack.Outputs.TaskExecutionRoleArn
  #
  # End of Section: ECS cluster
  #

  #
  # Section: Monitoring and Logging
  #
  DashboardsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./dashboards.yaml
      Parameters:
        ALBFullName: !GetAtt EcsClusterStack.Outputs.ALBFullName
        ClusterName: !GetAtt EcsClusterStack.Outputs.ClusterName
        FontColorServiceName: !GetAtt FontColorServiceStack.Outputs.ServiceName
        FontSizeServiceName: !GetAtt FontSizeServiceStack.Outputs.ServiceName
        FrontendServiceName: !GetAtt FrontendServiceStack.Outputs.ServiceName
        WordServiceName: !GetAtt WordServiceStack.Outputs.ServiceName
        WorkerNodeASGName: !GetAtt EcsClusterStack.Outputs.WorkerNodeASGName

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /microservices
      RetentionInDays: !Ref LogRetentionPeriod
  #
  # End of Section: Monitoring and Logging
  #

  #
  # Section: Continuous Deployment
  #
  PipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./pipeline.yaml
      Parameters:
        EcsClusterName: !GetAtt EcsClusterStack.Outputs.ClusterName
        FrontendImageUri: !Ref FrontendImageUri
        FrontendServiceName: !GetAtt FrontendServiceStack.Outputs.ServiceName
  #
  # End of Section: Continuous Deployment
  #

  #
  # Section: Automation
  #
  AutomationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./automation.yaml
      Parameters:
        AL2AmiId: !Ref AL2AmiId
        CodeCommitRepositoryArn: !GetAtt PipelineStack.Outputs.CodeCommitRepositoryArn
        CodeCommitRepositoryName: !GetAtt PipelineStack.Outputs.CodeCommitRepositoryName
        FrontendServiceEcrRepoName: !GetAtt PipelineStack.Outputs.FrontendServiceEcrRepoName
        SourceRepo: !Ref SourceRepo
        SubnetId: !GetAtt NetworkStack.Outputs.PrivateSubnetAId
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
  #
  # End of Section: Automation
  #

Outputs:
  FrontendUrl:
    Description: The URL to the Application Load Balancer fronting the cluster.
    Value: !Join ['', ['http://', !GetAtt EcsClusterStack.Outputs.ALBDNSName]]
