Parameters:
  ClusterArn:
    Type: String
  ClusterName:
    Type: String
  # ClusterSecurityGroupId:
  #   Type: String
  WorkerImageUri:
    Type: String
  JobQueueUrl:
    Type: String
  LogGroup:
    Type: String
  PrivateSubnetAId:
    Type: String
  PrivateSubnetBId:
    Type: String
  # ServiceRegistryNamespaceId:
  #   Type: String
  TaskExecutionRoleArn:
    Type: String

Resources:
  # FontColorServiceRegistry:
  #   Type: AWS::ServiceDiscovery::Service
  #   Properties:
  #     DnsConfig:
  #       DnsRecords:
  #         - TTL: 15
  #           Type: A
  #       NamespaceId: !Ref ServiceRegistryNamespaceId
  #       RoutingPolicy: MULTIVALUE
  #     Name: font-color

  WorkerTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: worker
          Environment:
            - Name: WORKER_SQS_QUEUE_URL
              Value: !Ref JobQueueUrl
          Image: !Ref WorkerImageUri
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: worker
          MemoryReservation: 512
          StopTimeout: 5
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE

  WorkerService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterArn
      # DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          # SecurityGroups:
          #   - !Ref ClusterSecurityGroupId
          Subnets:
            - !Ref PrivateSubnetAId
            - !Ref PrivateSubnetBId
      # ServiceRegistries:
      #   - RegistryArn: !GetAtt FontColorServiceRegistry.Arn
      TaskDefinition: !Ref WorkerTaskDef

  # FontColorSvcScalableTarget:
  #   Type: AWS::ApplicationAutoScaling::ScalableTarget
  #   Properties:
  #     MaxCapacity: 10
  #     MinCapacity: 2
  #     ResourceId: !Sub service/${ClusterName}/${FontColorService.Name}
  #     RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService'
  #     ScalableDimension: ecs:service:DesiredCount
  #     ServiceNamespace: ecs

  # FontColorSvcScaleUpPolicy:
  #   Type: AWS::ApplicationAutoScaling::ScalingPolicy
  #   Properties:
  #     PolicyName: FontColorSvcScaleUp
  #     PolicyType: StepScaling
  #     ScalingTargetId: !Ref FontColorSvcScalableTarget
  #     StepScalingPolicyConfiguration:
  #       AdjustmentType: ChangeInCapacity
  #       StepAdjustments:
  #         - MetricIntervalLowerBound: 0
  #           ScalingAdjustment: 2

  # FontColorSvcScaleDownPolicy:
  #   Type: AWS::ApplicationAutoScaling::ScalingPolicy
  #   Properties:
  #     PolicyName: FontColorSvcScaleDown
  #     PolicyType: StepScaling
  #     ScalingTargetId: !Ref FontColorSvcScalableTarget
  #     StepScalingPolicyConfiguration:
  #       AdjustmentType: ChangeInCapacity
  #       StepAdjustments:
  #         - MetricIntervalUpperBound: 0
  #           ScalingAdjustment: -1

  # FontColorSvcHighCpuAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmActions:
  #       - !Ref FontColorSvcScaleUpPolicy
  #     ComparisonOperator: GreaterThanOrEqualToThreshold
  #     DatapointsToAlarm: 1
  #     Dimensions:
  #       - Name: ClusterName
  #         Value: !Ref ClusterName
  #       - Name: ServiceName
  #         Value: !GetAtt FontColorService.Name
  #     EvaluationPeriods: 1
  #     MetricName: CPUUtilization
  #     Namespace: AWS/ECS
  #     Period: 60
  #     Statistic: Average
  #     Threshold: 30

  # FontColorSvcLowCpuAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmActions:
  #       - !Ref FontColorSvcScaleDownPolicy
  #     ComparisonOperator: LessThanThreshold
  #     DatapointsToAlarm: 1
  #     Dimensions:
  #       - Name: ClusterName
  #         Value: !Ref ClusterName
  #       - Name: ServiceName
  #         Value: !GetAtt FontColorService.Name
  #     EvaluationPeriods: 1
  #     MetricName: CPUUtilization
  #     Namespace: AWS/ECS
  #     Period: 60
  #     Statistic: Average
  #     Threshold: 15

# Outputs:
#   ServiceName:
#     Value: !GetAtt FontColorService.Name
