apiVersion: apps/v1
kind: Deployment
metadata:
  name: font-size
spec:
  selector:
    matchLabels:
      app: font-size
  replicas: 2
  template:
    metadata:
      labels:
        app: font-size
    spec:
      containers:
      - name: font-size
        image: carlosafonso/microservices-font-size
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 125m
            memory: 256Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: font-size
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: font-size
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: font-size
spec:
  selector:
    app: font-size
  type: ClusterIP
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
