apiVersion: apps/v1
kind: Deployment
metadata:
  name: font-color
spec:
  selector:
    matchLabels:
      app: font-color
  replicas: 2
  template:
    metadata:
      labels:
        app: font-color
    spec:
      containers:
      - name: font-color
        image: carlosafonso/microservices-font-color
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: font-color
spec:
  selector:
    app: font-color
  type: ClusterIP
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
