apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: carlosafonso/microservices-frontend
        ports:
        - containerPort: 8080
        env:
          - name: MICROSERVICES_ENV
            value: dev
          - name: FONT_COLOR_SVC
            value: font-color:80
          - name: FONT_SIZE_SVC
            value: font-size:80
          - name: WORD_SVC
            value: word:80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080