apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      env: dev
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
      - name: frontend
        image: carlosafonso/microservices-frontend
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 125m
            memory: 256Mi
        env:
          - name: MICROSERVICES_ENV
            value: dev
          - name: FONT_COLOR_SVC
            value: font-color:80
          - name: FONT_SIZE_SVC
            value: font-size:80
          - name: WORD_SVC
            value: word:80
          - name: MSVC_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MSVC_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
    env: dev
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
