---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word
spec:
  template:
    spec:
      containers:
      - name: word
        env:
          - name: USE_DATABASE
            value: "true"
          - name: FIRESTORE_COLLECTION_NAME
            value: msvc-prod-words
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: frontend
          env:
            - name: MICROSERVICES_ENV
              value: "prod"
            - name: FONT_COLOR_SVC
              value: font-color-prod:80
            - name: FONT_SIZE_SVC
              value: font-size-prod:80
            - name: WORD_SVC
              value: word-prod:80
            - name: PUBSUB_EVENTS_TOPIC
              value: msvc-prod-events
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    env: prod
