---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: frontend
          env:
            - name: MICROSERVICES_ENV
              value: "prod"
            - name: FONT_COLOR_SVC
              value: font-color-prod:80
            - name: FONT_SIZE_SVC
              value: font-size-prod:80
            - name: WORD_SVC
              value: word-prod:80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    env: prod
