---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: MICROSERVICES_ENV
              value: "staging"
