---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      env: staging
  template:
    metadata:
      labels:
        env: staging
    spec:
      containers:
        - name: frontend
          env:
            - name: MICROSERVICES_ENV
              value: "staging"
            - name: FONT_COLOR_SVC
              value: font-color-staging:80
            - name: FONT_SIZE_SVC
              value: font-size-staging:80
            - name: WORD_SVC
              value: word-staging:80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    env: staging
