version: 0.2

phases:
  pre_build:
    commands:
      - echo -n "$CODEBUILD_BUILD_ID" | sed "s/.*:\([[:xdigit:]]\{7\}\).*/\1/" > /tmp/build_id.out
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - printf '[{"name":"frontend","imageUri":"%s"}]' "$(cat /tmp/build_tag.out)" > imagedefinitions.json
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...

      - cd src/frontend
      - docker build -t "$(cat /tmp/build_tag.out)" .
      - docker push "$(cat /tmp/build_tag.out)"

      # Used only for ECS Blue/Green deployments
      - printf '{"ImageURI":"%s"}' "$(cat /tmp/build_tag.out)" > imageDetail.json
artifacts:
  files:
    - imagedefinitions.json
    - src/frontend/taskdef.json
    - src/frontend/appspec.yaml
    - src/frontend/imageDetail.json
  discard-paths: yes
