apiVersion: apps/v1
kind: Deployment
metadata:
  name: word
spec:
  selector:
    matchLabels:
      app: word
  replicas: 2
  template:
    metadata:
      labels:
        app: word
    spec:
      containers:
      - name: word
        image: carlosafonso/microservices-word
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: word
spec:
  selector:
    app: word
  type: ClusterIP
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
