name: Push images to Docker Hub

on:
  push:
    branches: [ "master" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push frontend service
      uses: docker/build-push-action@v2
      with:
        context: ./src/frontend
        file:  ./src/frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservices-frontend:latest

  build-font-color:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push font-color service
      uses: docker/build-push-action@v2
      with:
        context: ./src/font-color
        file:  ./src/font-color/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservices-font-color:latest

  build-font-size:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push font-size service
      uses: docker/build-push-action@v2
      with:
        context: ./src/font-size
        file:  ./src/font-size/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservices-font-size:latest

  build-word:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push word service
        uses: docker/build-push-action@v2
        with:
          context: ./src/word
          file:  ./src/word/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservices-word:latest

  build-worker:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push worker service
        uses: docker/build-push-action@v2
        with:
          context: ./src/worker
          file:  ./src/worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservices-worker:latest

  build-load-generator:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push load-generator service
        uses: docker/build-push-action@v2
        with:
          context: ./src/load-generator
          file:  ./src/load-generator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservices-load-generator:latest
